### PR TITLE
Htmlize

### PR DESCRIPTION
**Pull request by mattn**
added `--html` to output html.

See http://mattn.kaoriya.net/tmp/ccat-html.html

This is output of:
```
$ ccat --html main.go
```

### CODE REVIEW

**Comment by jingweno** [comment]
This is looking great! Thanks!

**Comment by shaggytwodope** [comment]
@jingweno Noticed you bumped version for this, any plans to make a release snapshot?

**Comment by jingweno** [comment]
@shaggytwodope Yes, please see https://github.com/jingweno/ccat/releases/tag/v1.1.0.

**Comment by mattn** [comment]
:+1:

**Pull request merged**
