### PR TITLE
Fix bug that `ccat` for stdin doesn’t work when EOF is sent

### PR DESCRIPTION
**Pull request by jingweno**
Details see https://github.com/golang/go/issues/10735

### CODE REVIEW

**Comment by mattn** [comment]
I'm thinking golang.org/x/crypto/ssh/terminal to bigger for doing it.
How about this? https://github.com/mattn/go-isatty

**Comment by jingweno** [comment]
@mattn I assume you meant [this commit](https://github.com/jingweno/ccat/commit/25c0ff0882947c36556bcce03664c15e15cb1991)

**Comment by mattn** [comment]
Ah, sorry. Yes, you are right.
And I can suggest https://github.com/mattn/go-colorable to support windows.

**Comment by jingweno** [comment]
@mattn Good work of go-colorable. Would you be able to contribute a bit? Not using windows myself actively.

**Comment by mattn** [comment]
I'm not familier to godep. Could you please let me know how to update Godeps/* ?

**Comment by jingweno** [comment]
@mattn You just edit the code like you do without `godep`. You then run `godep save -r ./...` then it will pull in the dependencies. `-r` means rewrite the import paths of the dependency as well.

**Pull request closed without merging**
