### PR TITLE
Only colorize when the output is stdout

### PR DESCRIPTION
**Pull request by gilliek**

### CODE REVIEW

**Comment by jingweno** [comment]
The code looks good. But could you give me a use case of not using `ccat` in a terminal?

**Comment by gilliek** [comment]
Thanks :)

Simply ccat foo.go > bar.go ;-) One of the use case of cat(1). This way, ccat can be used as a replacement of cat(1).

**Comment by jingweno** [comment]
`ccat foo.go > bar.go` should work without your check of terminal since it outputs to stdout?

**Comment by jingweno** [comment]
Oh okay, or you want `ccat` to fall back to `cat` when there's a `>`?

**Comment by gilliek** [comment]
Yes it works, but it also outputs the color codes

**Comment by gilliek** [comment]
Precisely :)

**Comment by jingweno** [comment]
I'm thinking having a flag so that people could disable syntax highlighting like this: `ccat -p main.go > foo` (`p` stands for plain text). It's a more generic solution adapting to all cases.

**Comment by gilliek** [comment]
It could be nice too :)
But my point is that the output, outside of a terminal, is completely useless since the ANSI escape codes only works within a terminal so I see no reason in favor of colorizing when there is a `>`. I think it's more convenient to fallback to a `cat` like behavior in this very case.

**Comment by jingweno** [comment]
Ah, make sense :+1:. I merged it in https://github.com/jingweno/ccat/commit/25c0ff0882947c36556bcce03664c15e15cb1991

**Comment by gilliek** [comment]
Thanks :)

**Comment by Rolinh** [comment]
The behavior proposed by @gilliek  here is similar to `--color=auto` on some GNU tools (see `ls` man page for instance) and is the expected behavior by most users I'd say. I would not use a new flag for that and as @gilliek  stated, there is no point in having ANSI escape codes  in a text file.

**Comment by jingweno** [comment]
@Rolinh Sure, the change is in master, feel free to try it out :smiley_cat:

**Pull request closed without merging**
